# Generated by Django 3.2.5 on 2021-08-23 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_variation_category'),
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.variation'),
        ),
    ]
