# Generated by Django 3.2.5 on 2021-09-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_orderlineitem_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='variation',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='product_variation',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
