# Generated by Django 3.2.5 on 2021-11-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20210926_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_variation',
        ),
    ]
