# Generated by Django 3.2.5 on 2021-07-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210723_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('type', 'type'), ('duration', 'duration')], default='type', max_length=120),
        ),
    ]
