# Generated by Django 3.2.5 on 2021-07-24 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_variation_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='category',
        ),
    ]
