# Generated by Django 3.2.5 on 2021-09-12 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_variation_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
