# Generated by Django 3.2.5 on 2021-09-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210912_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='image',
        ),
    ]
